import { parse } from '@babel/parser'
import type { NodePath } from '@babel/traverse'
import * as t from '@babel/types'
import * as path from 'path'

import type { Helper } from './webpack-helper'
import { concatHelper, WEBPACK_HELPER_ID } from './webpack-helper'
import { formatSource } from '../uncompress'
import type {
    BundlerStrategy,
    BundleSource,
    ModuleGraph,
    ModuleID,
    ModuleInfo,
    Tip,
    TransformContext,
} from './types'

export class Extractor {
    tips: Tip[] = []
    helpers: Set<Helper> = new Set()
    private strategy: BundlerStrategy
    private ctx: TransformContext

    constructor(strategy: BundlerStrategy) {
        this.strategy = strategy
        this.ctx = {
            tips: this.tips,
            helpers: this.helpers,
            rewrite: id => this.rewrite(id),
        }
    }

    /**
     * The function recvives the original id and returns the filename of code file.
     * If your want to change the filename, this will help.
     * @param id module ID
     * @returns Rewrited ID
     */
    rewrite(id: ModuleID): string {
        if (id === WEBPACK_HELPER_ID) {
            return WEBPACK_HELPER_ID + '.cjs'
        }
        return id + '.cjs'
    }

    async graph(sources: BundleSource[]): Promise<ModuleGraph> {
        const graph: ModuleGraph = {}

        for (const source of sources) {
            let ast
            try {
                ast = parse(source.content)
            } catch {
                // 文件无法解析（可能混入了坏产物），跳过
                continue
            }
            let modulesPath: NodePath<t.ObjectExpression>
            try {
                modulesPath = this.strategy.locate(ast)
            } catch {
                // 该文件不是本类型的 bundle（可能混入了普通文件/其他类型产物），跳过
                continue
            }

            modulesPath.node.properties.forEach((property, index) => {
                if (t.isObjectProperty(property)) {
                    let key: string
                    if (t.isNumericLiteral(property.key)) {
                        key = property.key.value.toString()
                    } else if (t.isIdentifier(property.key)) {
                        key = property.key.name
                    } else if (t.isStringLiteral(property.key)) {
                        key = property.key.value
                    } else {
                        return
                    }
                    const propPath = modulesPath.get(
                        `properties.${index}`
                    ) as NodePath<t.ObjectProperty>
                    const moduleInfo = this.strategy.transform(
                        this.ctx,
                        key as ModuleID,
                        propPath
                    )

                    graph[key as ModuleID] = {
                        ...moduleInfo,
                        filename: source.filename,
                        name: this.rewrite(key as ModuleID),
                    }
                }
            })
        }
        return graph
    }

    analyze(modules: ModuleGraph) {
        const refmap: Record<ModuleID, Set<ModuleID>> = {}
        for (const [id, info] of Object.entries(modules)) {
            for (const dep of info.dependcies) {
                if (!refmap[dep]) {
                    refmap[dep] = new Set()
                }
                refmap[dep].add(id as ModuleID)
            }
        }
        for (const id of Object.keys(modules) as ModuleID[]) {
            modules[id].referredBy = refmap[id] || new Set()
        }
    }

    /** 生成单个模块的输出（banner + 格式化代码），不落盘 */
    async emit(
        module: ModuleInfo
    ): Promise<{ filename: string; content: string }> {
        const problems = this.tips
            .filter(tip => tip.module === module.id)
            .map(({ type, src }) => {
                src = src.replaceAll(/\/\*(.*?)\*\//g, '')
                return `${type} -> ${src}`
            })
        const deps = [...module.dependcies].map(dep => this.rewrite(dep))
        const referredBy = module.referredBy
            ? [...module.referredBy].map(mod => this.rewrite(mod))
            : null

        const banner = `/**
 * Filename: ${this.rewrite(module.id)}
 * Bundle Name: ${module.filename}
 *
 * This file is a part of bundle ${path.basename(
     module.filename
 )} and is automatically 
 * generated by the decompile tool for reference only.
 * 
 * The author of the tool is not responsible for any consequences 
 * caused by the use of the tool, and the copyright belongs to 
 * the author of the original source code. Do not distribute.
 * 
 * Depends: ${deps.length ? deps.join(', ') : 'None'}
 * 
 * Referred by: ${
     referredBy === null
         ? 'Data missing'
         : referredBy.length
           ? referredBy.join(', ')
           : 'None'
 }
 * 
 * ${
     problems.length
         ? 'Problems:' + problems.map(p => '\n * ' + p).join('')
         : 'No problem found in this file :)'
 }
 */
`

        const source = await formatSource(module.ast)
        return {
            filename: this.rewrite(module.id),
            content: banner + source,
        }
    }

    /** 生成 webpack helper 输出（如无 helper 返回 null），不落盘 */
    async emitHelper(): Promise<{ filename: string; content: string } | null> {
        const code = concatHelper(this.helpers)
        if (!code) {
            return null
        }
        return {
            filename: this.rewrite(WEBPACK_HELPER_ID as ModuleID),
            content: code,
        }
    }

    formatTips() {
        let strings: string[] = []
        for (const tip of this.tips) {
            const { module, type, src } = tip
            strings.push(`${type} from ${this.rewrite(module)}: ${src}`)
        }
        return strings.join('\n')
    }
}
